version: '3'

services:
  my-app:
    image: my-app
    container_name: my-app
    build:
      context: .
      dockerfile: Dockerfile   
    ports:
      - 3000:3000
      
  mongodb:
    image: mongo
    container_name: my-app
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=p4ssw0rd
    volumes:
      - ./mongo-data:/data/db
      
  mongo-express:
    image: mongo-express
    container_name: my-app
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=p4ssw0rd
      - ME_CONFIG_MONGODB_SERVER=mongodb

